language: nix

nix: 2.2.2

script:
  - nix-env -iA cachix -f https://cachix.org/api/v1/install
  - cachix use werbematerial-gh-pages
  - nix-build --argstr public-url '/werbematerial'

cache:
  directories:
    - /nix/store

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: result/
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
