---
name: GitHub Pages
on:
  push:
    branches: [master]

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-22.11
      - uses: cachix/cachix-action@v12
        with:
          name: s77-werbematerial
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

      - name: generate site
        run: nix-build --argstr public-url '/werbematerial'

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./result
