name: GiHub Pages
on:
  push:
    branches: [master]

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v6
      - uses: cachix/cachix-action@v3
        with:
          name: s77-werbematerial
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

      - name: generate site
        run: nix-build --argstr public-url '/werbematerial'

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./result